### ISSUE TITLE
Android 7

### ISSUE THREAD

**Issue by swiferlf** [TeamWin/android_device_bq_tenshi#1]
it works very good with android 6, but with the new update to android 7, TWRP is mirrored in the phone, i mean, you must handle touch recovery touching as if it is in the right direction, but watching TWRP as if it is rotated 180º. could you please take a look at it? thanks!

**Comment by Kra1o5** [comment]
Hi @swiferlf ,

It will be fixed in 3.1.0.1.

I will let you know when this go out (asap).

Greetings

**Comment by cypx** [comment]
Same issue here with 3.2.1 and 3.2.0.
I'm going to try 3.1.0.1 but the flipped screen config seems to be missing since 6237a0c6fde806992f6c8cba48862996a855fcfa

**Comment by cypx** [comment]
```
BOARD_HAS_FLIPPED_SCREEN := true
```
Seems to be needed on my Aquaris U Plus.
Builds before commit (twrp-3.1.0-0-tenshi.img and twrp-3.0.2-0-tenshi.img on https://dl.twrp.me/tenshi/ ) are working but all build after commit have upside down screen.

**Comment by Kra1o5** [comment]
Hi @cypx, 

The latest version works fine for N firmwares if you have M firmware as base use old version.

Regards,

**Comment by cypx** [comment]
Hi @Kra1o5 

Thanks for explanations!
I have to reinstall official BQ M rom (1.5) to get N update including new fastboot version (2.5.0) and after that I could install up to date TWRP and LineageOS without upside down screen problem.

**Comment by Kra1o5** [comment]
Hi @cypx,

You can flash official N (fastboot) directly no need to flash M first.

Greetings

**Comment by cypx** [comment]
@Kra1o5 

I try before, but guess what? Upside down screen with official rom -.-

I don't know why, but when I try to flash official N using USB (and the .sh file included into official zip cause BQ flash app ask for a security file), the fastboot firmware do not get updated (so I have 1.5 fastboot with a offficial N rom and upside down screen).
So I retry using OTA update from M rom and all goes fine. 

Thanks again for your support!

**Comment by Kra1o5** [comment]
@cypx Great!
@Dees-Troy We can close this issue now.
Thanks
